# Generated by Django 4.1.5 on 2023-01-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=256)),
                ('starting_bid', models.IntegerField()),
                ('image', models.URLField(max_length=256)),
                ('category', models.CharField(max_length=32)),
            ],
        ),
    ]
