# Generated by Django 4.1.5 on 2023-01-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_comment_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
