# Generated by Django 4.1.5 on 2023-01-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_remove_watchlist_items_watchlist_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='items',
            new_name='item',
        ),
    ]
